# Tên ứng dụng Spring
spring:
  application:
    name: 5TProMart
  
  # --- CẤU HÌNH DATABASE (PostgreSQL) ---
  datasource:
    url: jdbc:postgresql://localhost:5432/fivetpromart_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # --- CẤU HÌNH JPA/HIBERNATE ---
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # --- CẤU HÌNH JACKSON (JSON) ---
  jackson:
    serialization:
      indent_output: true

  # --- CẤU HÌNH BẢO MẬT (RESOURCE SERVER) ---
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/fivetpro

# --- CẤU HÌNH SERVER ---
server:
  port: 8080

# --- CẤU HÌNH LOGGING ---
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.fivetpromart.infrastructure.identity.keycloak.client: DEBUG
    feign: DEBUG

# --- CẤU HÌNH IDP (Keycloak) (dùng cho Feign Client/Adapter) ---
idp:
  url: http://localhost:8180
  realm: fivetpro
  client-id: fivetpro
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

# --- CẤU HÌNH APP (OTP) ---
app:
  otp:
    secret: ${APP_OTP_SECRET}
    ttl-seconds: 600
    max-attempts: 5
  signup:
    cleanup-millis: 3600000

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: ${BREVO_API_KEY}
    sender-email: tinvo2005@gmail.com
    sender-name: FiveTProMart Corp.